// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Talleres.Infraestructura.Persistencia;

#nullable disable

namespace Talleres.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(TallerDbContext))]
    [Migration("20260813162609_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Talleres.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "DocumentoIdentidad")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "Nombre");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.HistorialOrdenServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("OrdenServicioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioId");

                    b.HasIndex("EmpresaId", "OrdenServicioId", "Fecha");

                    b.ToTable("HistorialOrdenesServicio", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.OrdenServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("VehiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("EmpresaId", "FechaIngreso");

                    b.HasIndex("EmpresaId", "Numero")
                        .IsUnique();

                    b.ToTable("OrdenesServicio", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.RecepcionVehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DejaDocumentos")
                        .HasColumnType("bit");

                    b.Property<bool>("DejaLlaves")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<long>("OrdenServicioId")
                        .HasColumnType("bigint");

                    b.Property<byte>("PorcentajeCombustible")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioId")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "OrdenServicioId")
                        .IsUnique();

                    b.ToTable("RecepcionesVehiculo", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecepcionesVehiculo_PorcentajeCombustible", "[PorcentajeCombustible] >= 0 AND [PorcentajeCombustible] <= 100");
                        });
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NumeroVin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId", "ClienteId");

                    b.HasIndex("EmpresaId", "Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehiculos_Anio", "[Anio] >= 1900 AND [Anio] <= 2100");
                        });
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.HistorialOrdenServicio", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.OrdenServicio", "OrdenServicio")
                        .WithMany("Historial")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.OrdenServicio", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talleres.Dominio.Entidades.Vehiculo", "Vehiculo")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.RecepcionVehiculo", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.OrdenServicio", "OrdenServicio")
                        .WithOne("Recepcion")
                        .HasForeignKey("Talleres.Dominio.Entidades.RecepcionVehiculo", "OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.Vehiculo", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("OrdenesServicio");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.OrdenServicio", b =>
                {
                    b.Navigation("Historial");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Navigation("OrdenesServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
