// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Talleres.Infraestructura.Persistencia;

#nullable disable

namespace Talleres.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(TallerDbContext))]
    [Migration("20260911011906_HacerIdentificacionClienteOpcional")]
    partial class HacerIdentificacionClienteOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Talleres.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "DocumentoIdentidad")
                        .IsUnique()
                        .HasFilter("[DocumentoIdentidad] IS NOT NULL");

                    b.HasIndex("EmpresaId", "Nombre");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.DanioVehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("RecepcionVehiculoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Severidad")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("Zona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionVehiculoId");

                    b.HasIndex("EmpresaId", "RecepcionVehiculoId");

                    b.ToTable("DaniosVehiculo", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.DetalleOrdenServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BodegaInventarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CodigoProducto")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ExistenciaDescontada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("OrdenServicioId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ProductoInventarioId")
                        .HasColumnType("int");

                    b.Property<int?>("SalidaInventarioId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioId");

                    b.HasIndex("EmpresaId", "OrdenServicioId");

                    b.HasIndex("EmpresaId", "SalidaInventarioId");

                    b.ToTable("DetallesOrdenesServicio", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.EvidenciaDiagnostico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClaveObjeto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCargaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("Longitud")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("OrdenServicioId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClaveObjeto")
                        .IsUnique();

                    b.HasIndex("OrdenServicioId");

                    b.HasIndex("EmpresaId", "OrdenServicioId");

                    b.ToTable("EvidenciasDiagnostico", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.EvidenciaInspeccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClaveObjeto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCargaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("Longitud")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("RecepcionVehiculoId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClaveObjeto")
                        .IsUnique();

                    b.HasIndex("RecepcionVehiculoId");

                    b.HasIndex("EmpresaId", "RecepcionVehiculoId");

                    b.ToTable("EvidenciasInspeccion", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.HistorialOrdenServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("OrdenServicioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioId");

                    b.HasIndex("EmpresaId", "OrdenServicioId", "Fecha");

                    b.ToTable("HistorialOrdenesServicio", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.MarcaVehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("MarcasVehiculo", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.ModeloVehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("MarcaVehiculoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "MarcaVehiculoId", "Nombre")
                        .IsUnique();

                    b.ToTable("ModelosVehiculo", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.OrdenServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAutorizacionClienteUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("FechaDiagnosticoUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TokenPublico")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("VehiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TokenPublico")
                        .IsUnique()
                        .HasFilter("[TokenPublico] IS NOT NULL");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("EmpresaId", "FechaIngreso");

                    b.HasIndex("EmpresaId", "Numero")
                        .IsUnique();

                    b.ToTable("OrdenesServicio", (string)null);
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.RecepcionVehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DejaDocumentos")
                        .HasColumnType("bit");

                    b.Property<bool>("DejaLlaves")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<long>("OrdenServicioId")
                        .HasColumnType("bigint");

                    b.Property<byte>("PorcentajeCombustible")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioId")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "OrdenServicioId")
                        .IsUnique();

                    b.ToTable("RecepcionesVehiculo", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecepcionesVehiculo_PorcentajeCombustible", "[PorcentajeCombustible] >= 0 AND [PorcentajeCombustible] <= 100");
                        });
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.TallerSincronizado", b =>
                {
                    b.Property<int>("EmpresaNovaId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaConfiguracionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("EmpresaNovaId");

                    b.HasIndex("Activo");

                    b.ToTable("TalleresSincronizados", (string)null);

                    b.HasData(
                        new
                        {
                            EmpresaNovaId = 3071,
                            Activo = true,
                            FechaConfiguracionUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("ModeloVehiculoId")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroVin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId", "ClienteId");

                    b.HasIndex("EmpresaId", "ModeloVehiculoId");

                    b.HasIndex("EmpresaId", "Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehiculos_Anio", "[Anio] >= 1900 AND [Anio] <= 2100");
                        });
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.DanioVehiculo", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.RecepcionVehiculo", "RecepcionVehiculo")
                        .WithMany("Danios")
                        .HasForeignKey("RecepcionVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecepcionVehiculo");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.DetalleOrdenServicio", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.OrdenServicio", "OrdenServicio")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.EvidenciaDiagnostico", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.OrdenServicio", "OrdenServicio")
                        .WithMany("EvidenciasDiagnostico")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.EvidenciaInspeccion", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.RecepcionVehiculo", "RecepcionVehiculo")
                        .WithMany("Evidencias")
                        .HasForeignKey("RecepcionVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecepcionVehiculo");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.HistorialOrdenServicio", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.OrdenServicio", "OrdenServicio")
                        .WithMany("Historial")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.ModeloVehiculo", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.MarcaVehiculo", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("EmpresaId", "MarcaVehiculoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.OrdenServicio", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talleres.Dominio.Entidades.Vehiculo", "Vehiculo")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.RecepcionVehiculo", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.OrdenServicio", "OrdenServicio")
                        .WithOne("Recepcion")
                        .HasForeignKey("Talleres.Dominio.Entidades.RecepcionVehiculo", "OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.Vehiculo", b =>
                {
                    b.HasOne("Talleres.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talleres.Dominio.Entidades.ModeloVehiculo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("EmpresaId", "ModeloVehiculoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("OrdenesServicio");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.MarcaVehiculo", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.ModeloVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.OrdenServicio", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("EvidenciasDiagnostico");

                    b.Navigation("Historial");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.RecepcionVehiculo", b =>
                {
                    b.Navigation("Danios");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("Talleres.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Navigation("OrdenesServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
